### ISSUE TITLE
Calculate-Min-fee command

### ISSUE THREAD

**Issue by QuantumT95** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#2]
![InkedCapture_LI](https://user-images.githubusercontent.com/27324463/142293008-cbdf1091-26ec-48fa-a073-d70bdbec5872.jpg)
![InkedCapture1_LI1](https://user-images.githubusercontent.com/27324463/142293017-66943889-4091-4b5d-a261-3cddbba8dbde.jpg)

Came across this when I was trying to redeem my Ada back - How would I fix this?

**Comment by Murkey-git** [comment]
Hey, it looks like the script is having troubles opening the file "C:\Users\{USER}\bulk-nft\address\protocol.json". Can you confirm if this file exists?

You should be able to generate the file by running the following powershell commands, replacing the `{USER}` with your username:
```
cd "C:\Users\{USER}\bulk-nft\"
$BASE_PATH = "C:\Users\{USER}\bulk-nft\address"
$NODE_PATH = (Get-WmiObject Win32_Process -Filter "name = 'cardano-node.exe'" | Select-Object ExecutablePath).ExecutablePath
$CLI_PATH = [System.IO.Path]::Combine((Get-Item $NODE_PATH).Directory.FullName, "cardano-cli.exe")
$socket_path = (Get-WmiObject Win32_Process -Filter "name = 'cardano-node.exe'" | Select-Object CommandLine).CommandLine.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)[3]
$env:CARDANO_NODE_SOCKET_PATH = $socket_path
$protocolFile = [System.IO.Path]::Combine($BASE_PATH, "protocol.json")
&$CLI_PATH query protocol-parameters --mainnet --out-file "$protocolFile"
```

Let me know if that works for you

**Comment by QuantumT95** [comment]
> Hey, it looks like the script is having troubles opening the file "C:\Users{USER}\bulk-nft\address\protocol.json". Can you confirm if this file exists?
> 
> You should be able to generate the file by running the following powershell commands, replacing the `{USER}` with your username:
> 
> ```
> cd "C:\Users\{USER}\bulk-nft\"
> $BASE_PATH = "C:\Users\{USER}\bulk-nft\address"
> $NODE_PATH = (Get-WmiObject Win32_Process -Filter "name = 'cardano-node.exe'" | Select-Object ExecutablePath).ExecutablePath
> $CLI_PATH = [System.IO.Path]::Combine((Get-Item $NODE_PATH).Directory.FullName, "cardano-cli.exe")
> $socket_path = (Get-WmiObject Win32_Process -Filter "name = 'cardano-node.exe'" | Select-Object CommandLine).CommandLine.Split(" ",[System.StringSplitOptions]::RemoveEmptyEntries)[3]
> $env:CARDANO_NODE_SOCKET_PATH = $socket_path
> $protocolFile = [System.IO.Path]::Combine($BASE_PATH, "protocol.json")
> &$CLI_PATH query protocol-parameters --mainnet --out-file "$protocolFile"
> ```
> 
> Let me know if that works for you

The JSON wasn't in the file so I generated one using the powershell commands! Thanks for the help!

**Comment by Murkey-git** [comment]
No problem, glad it's resolved!
