### ISSUE TITLE
Build creating a shorter address

### ISSUE THREAD

**Issue by JPBrier** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#3]
Hello, 

I've tried to use the script on a drop today and got refunded on all transactions. The dev said that his team refunded all shorter addresses like the ones that the Build is generating, because they didnt identified as a "wallet" addresses (such as Yoroi, Daedalus addresses).

Example of a normal address: 
addr1qyr5rnlkxaazuanxxln7lzvm93mltsg0szad63lq2kmcu7leq9cjqyc5rlggmldrstrus4zf8mp3r77dqh28n89aly7s262r4a

Example of the address that Build is generating: 
addr1vy3klw0dnunxlwvh73llgl2p6hskm298mjthem38hg7492s92z6yh

Any solution on your script to this ?

**Comment by Murkey-git** [comment]
Hello,

That seems to be a common tactic lately to prevent sending assets to people using the CLI. I've just updated the script to generate wallet addresses which includes a staking key, so it should now match the same style of Daedalus and other common wallets (using the 104 character format).

**Comment by JPBrier** [comment]
Worked like a charm, thx :)

**Comment by Murkey-git** [comment]
No problem!
