### ISSUE TITLE
Possibility to send multiple transactions from 1 address

### ISSUE THREAD

**Issue by JPBrier** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#4]
Hey,

Could it be possible to send multiple transactions from just 1 address ? Some upcoming drops requires to hold atleast 1 CNFT from their collection on the wallet to be able to mint, so it would be nice to have some functionality like this.

Thanks.

**Comment by Murkey-git** [comment]
Hello,

I have updated the script to include the new BulkSend module.

As an example, to send 3 batches of 15 ADA to an address, you could run the following command:
`.\purchase.ps1 -count 3 -bulkcost 15 -bulkreceiver addr1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa`

Note that the code only uses a single UTXO for sending multiple transaction outputs. Therefore, if you were to perform the above command, you should send at least 47 ADA in a single transaction to the generated wallet.

Finally, if there is a prerequisite to hold an existing CNFT, then this CNFT must be sent in a separate transaction as the ADA used for funding. Using the example above, you would send one transaction of exactly 47 ADA, followed by a second transaction of any CNFTs required to hold.

Hope this helps.
