### ISSUE TITLE
Compatible with mac osx?

### ISSUE THREAD

**Issue by jonteho** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#5]
Hi,

Just a question, is this script compatible with powershell for mac osx?

Regards
Jonathan

**Comment by Murkey-git** [comment]
Hello,

I don't believe this will be compatible with mac osx as the script is utilizing various calls that assume a Windows environment.

That said, I've never used powershell for mac osx or tried the script in that environment, so I can't rule it out for certain. It may internally map all of the windows-specific functionality to something suitable for mac osx envrionment. 

If you'd like to know for certain, the best bet would be to try running the [Build] and [Verify] steps at a minimum to see if they execute successfully. If it works, I'd try funding 2-3 ADA to the script wallet, and then attempt to run the [Send] or [Redeem] commands back to your primary wallet.
