### ISSUE TITLE
ValueNotConservedUTxO Error

### ISSUE THREAD

**Issue by junshenlye** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#6]
i have 2 nfts with some ada in the wallet, when i tried to send it back to my wallet. it is only able to retreive 1 nft and all my ada which causes the error since nft have lock up ada.
![Screenshot 2022-01-31 055913](https://user-images.githubusercontent.com/69711881/151719600-b22bf56b-045c-44c0-80a4-3b8999ddf6a3.png)

**Comment by Murkey-git** [comment]
Hi there,

It looks like the latest version of Daedalus CLI has slightly changed the format of outputs which were relied upon for parsing out the actual tokens.

I've modified the script to parse for the new value "TxOutDatumNone" which will hopefully resolve your issue. Could you try the latest script and let me know if it resolves the issue?

**Comment by junshenlye** [comment]
Still doesnt work

**Comment by junshenlye** [comment]
i actually attempted the script for 2 projects 2 days ago, it worked fine.

**Comment by junshenlye** [comment]
suddenly i dont understand what environment changed that lead to this problem

**Comment by junshenlye** [comment]
![Screenshot 2022-01-31 075249](https://user-images.githubusercontent.com/69711881/151723157-35f55117-39b2-4f7d-ad02-81585df5693d.png)

**Comment by Murkey-git** [comment]
Oops! Sorry, just realized the other issue is with only pulling the single asset which you highlighted in the original post. Apologies for missing that.

I'll take a quick look at the code and do some testing to loop over all the tokens so they're properly redeemable. Will post back with an update when this is resolved.

**Comment by junshenlye** [comment]
No problem. Appreciate Your help!

**Comment by Murkey-git** [comment]
I've just updated the code with what I believe should now resolve the claiming issue of multiple tokens.

Still waiting on transactions to go through on the chain to test it, but simulated data seems to work fine.

I've updated the main branch if you'd like to give it a shot.

**Comment by Murkey-git** [comment]
My test transaction went through and was able to successfully handle multiple NFTs from the same UTXO, so I believe this issue should be resolved.

Please let me know if you experience anything differently from your end.

**Comment by junshenlye** [comment]
Hey thanks, finally I withdrew everything, thanks. The new script turns out fine. Appreciate your time and effort
