### ISSUE TITLE
new user

### ISSUE THREAD

**Issue by shinrajunn** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#7]
hi i am new here and i do not really know how to use power shell
i not very sure how to edit the addresses or key in addresses
i got this error. is there any tutorial on youtube i can watch 

& : The term 'C:\Cardano C:\Program Files\Daedalus Mainnet\cardano-cli.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At C:\Users\user\Desktop\Cardano-CNFT-Bulk-Purchaser-main\Cardano-CNFT-Bulk-Purchaser-main\purchase.ps1:112 char:8
+       &$CLI_PATH address key-gen --verification-key-file "$verifyKeyF ...
+        ~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Cardano C:\P...cardano-cli.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Murkey-git** [comment]
Hi,

You shouldn't need to edit anything in the script. The script will build the addresses for you and report those values; all you are required to do is fund the new wallets.

1. Can you confirm if you've modified the script? If so, you should undo any modifications and revert back to a fresh copy of the script.

2. Also, what was the exact command you executed on the command line? This will be useful in identifying the actual error.

Unfortunately, I do not have any resources to provide training.

**Comment by shinrajunn** [comment]
ok.. i think i got 2 node running which caused the error above. solved it already. my next error is no utxo
may i know how to fund my address? i dont really get it

![image](https://user-images.githubusercontent.com/98775301/151868671-b7c7bafb-710b-480f-9ffb-0e6a0051aa60.png)

**Comment by Murkey-git** [comment]
You need to send ADA to the addresses you hid in the screenshot using your regular wallet (presumably a wallet that's in Daedalus, Yoroi, or some other 3rd party wallet). Due to network congestion, this may take some time. Once the blockchain has verified the transaction, the `-count 3 -verify` command will return details of the UTXO in the new wallets.

Basically, this tool will generate several new hot wallets that you can fund prior to an NFT drop. When the NFT drop releases the minting address, you can use the `send` option and specify the cost of each NFT and the minting address. The script then loops through each of the wallets you created/funded, and sends each transaction. It can sign and send multiple transactions per second, which can give an advantage over users who are utilizing a regular wallet like Daedalus as it sends faster and in higher volume. After the NFTs are minted to your script wallets, you can run the `verify` option to view its received the NFT, followed by the `redeem` option to claim them back to your primary wallet.

**Comment by Murkey-git** [comment]
One more note: I would recommend if you are inexperienced or unclear of how this all works, I would recommend  backing up the addresses you built (rename the folder) and just run a `-count 1 -build`. Then send 5 ADA or something small to that address.

Then you can run a `-count 1 -verify` periodically until the wallet contains the funds.
Then you could run a `-count 1 -cost 2 -receiver YOUR-PRIMARY-WALLET-ADDRESS`

Once that transaction goes through, re-run the `verify` and try to reclaim the remaining ~3 ADA with the command `-count 1 -wallet YOUR-PRIMARY-WALLET-ADDRESS`.

This would basically simulate the typical flow of the script.

You will lose a small amount of the original 5 ADA in transaction fees, but hopefully it will clear up how the tool works.

**Comment by shinrajunn** [comment]
i am doing it correctly right? i just need to fund the wallet address given so that the script address will send to the payment address. am i correct? 

![image](https://user-images.githubusercontent.com/98775301/151871682-798e6b35-07fb-4a76-85e2-321288030baf.png)

**Comment by Murkey-git** [comment]
Yes, so you can see the address when it was generated on the command line, or find the address in the `payment1.addr`, `payment2.addr`, etc files. If you send some ADA to that address, the script will be able to pick it up. You can open these files in a text editor like notepad.

Note that those files are hot wallets and all the keys are present for signing transactions using those wallets. If you delete these files whatever ADA is sent to them will be permanently lost. If someone is able to view the contents of these files, they will be able to send transactions and potentially take any ADA within. Please make sure these files are kept secure.

**Comment by shinrajunn** [comment]
so.. the address given to me is a "script wallet" aka a new hot wallet that is not using any of my old address in daedalus. what if i want to take my ADA back to my original wallet? i still can send them back to myself is it?

**Comment by Murkey-git** [comment]
Yes, that's correct - a "script wallet" is a good definition.

If you wish to reclaim the amount to your original wallet, you would generally use the `redeem` function. Running the command with no arguments provides an explanation:

```
PS D:\purchaser> .\purchase.ps1
********************************************************************************
* HELP MENU
*
* Modes: The purchase.ps1 module has 4 modes: [Build, Verify, Send, Redeem]
* [Build]: Build [-count N] number of new addresses and payment keys used for purchasing
* [Verify]: Verify [-count N] the contents of each generated address, to ensure it has the appropriate funds. The UTXO will be cached to optimize [Send] mode speed
* [Send]: Send [-count N -cost X -receiver addr] {X} ADA to the specified receiver {addr}, using {N} generated addresses
* [BulkSend]: Send [-count N -bulkcost X -bulkreceiver addr] {N*X} ADA to the specified receiver {addr}, using {N} transaction-outputs from a single generated address
* [Redeem]: Redeem [-count N -wallet addr] all ADA and purchased NFT back to owner wallet {addr}, using {N} generated addresses
*
* Arguments:
* -count: The number of wallets and addresses to build / verify / send / redeem from
* -build: Set the build flag to execute [Build] mode
* -verify: Set the verify flag to execute [Verify] mode
* -cost: The price in ADA that the [Send] mode will send to [-receiver] address
* -receiver: The address to send ADA to in [Send] mode - e.g., the wallet address for purchasing NFTs
* -bulkcost: The price in ADA that the [BulkSend] mode will send in each transaction output to [-bulkreceiver] address
* -bulkreceiver: The address to send ADA to in [BulkSend] mode - e.g., the wallet address for purchasing NFTs
* -wallet: The address to send ADA to in [Receive] mode - e.g., your own wallet for redeeming the NFTs and any dust
* -safemode: Set the [Send] or [Receive] mode to run in safety mode, and prompt for approval before sending assets
*
* Example scenario:
* .\purchase.ps1 -count 3 -build
* -- Verify That Wallets Are Populated And Cache UTXOs --
* .\purchase.ps1 -count 3 -verify
* .\purchase.ps1 -count 3 -cost 15 -receiver addr1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
* ----- Alternative Sending Method -----
* ----- Will send 15 ADA to addr1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa in 3 transaction outputs from a single wallet, for a total of 45 ADA cost -----
* .\purchase.ps1 -count 3 -bulkcost 15 -bulkreceiver addr1aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
* -- Verify That Wallets Received NFTs --
* .\purchase.ps1 -count 3 -verify
* .\purchase.ps1 -count 3 -safemode -wallet addr1bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
*
* If this script is useful for you, please consider donating ADA to the following address:
* addr1q9afhw5v8rkydmvd34kl6mjvllr58lsf8kjv8wnyftf73g4utnxgcn0srryfpc4tmlq0n9lr9w5uhzqax88dneyhs48q84wugk
*
*********************************************************************************
```

**Comment by shinrajunn** [comment]
ok thanks
