### ISSUE TITLE
Enhancement for bot

### ISSUE THREAD

**Issue by junshenlye** [Murkey-git/Cardano-CNFT-Bulk-Purchaser#8]

**Comment by Murkey-git** [comment]
Hello,

While this may be possible with some effort, I am unclear on which scenario you are referring to. I cannot say for certain whether the support is possible or not.

Scenario 1:
There is one source wallet funded with X ADA, and it is desirable to send X/Y ADA to Y destination addresses within a single UTXO

Scenario 2:
There are Y source wallets funded with X ADA, and it is desirable to send X*Y ADA (in Y quantities) to 1 destination address within a single UTXO

Scenario 3:
There are Y source wallets funded with X ADA, and it is desirable for each source wallet to send X ADA to Y destinations addresses within a single UTXO
